name: fifo-advisor
channels:
  - conda-forge
  - https://sharc-lab.github.io/LightningSim/repo
dependencies:
  - python=3.12
  - lightningsim=0.2.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - pymoo
  - joblib
  - ruff
  - mypy
